### ISSUE TITLE
Menu bar on small screens

### ISSUE THREAD

**Issue by erwindon** [maerteijn/SaltGUI#31]
The top row of the screen is becoming crowded on small screens (<800px). It shows the following items: logo, 2 regular menu items, logout button and run button.
Proposal is to apply 1 of the following 3 choices on small screens:
1) place the menu bar below logo/logout/run as a separate row; or
2) place the menu items in a dropdown menu, so that initially only the triangle-shaped indicator is visible; or
3) same as (2), but also move the logout button to be in that menu.

@maerteijn, your preference please?

Note that an extension of the menu bar to 3 items (or more) cannot be done before this is resolved.

**Comment by maerteijn** [comment]
I would say 3, and to move the logout button in the normal menu as well to be a bit more concistent

**Comment by maerteijn** [comment]
My suggestion is to solve it like this:

<img width="1158" alt="normal" src="https://user-images.githubusercontent.com/121401/43194817-9afeb240-9003-11e8-9fcb-2240e61bf365.png">

800 or less:

<img width="788" alt="responsive" src="https://user-images.githubusercontent.com/121401/43194837-a6c6fca4-9003-11e8-86fc-d9031e890b3f.png">

I changed the header html to this:

```html
    <header>
      <h1 class='logo'>SaltGUI</h1>
      <div class='menubar'>
        <div class='menu_item' id='button_minions'>minions</div>
        <div class='menu_item' id='button_keys'>keys</div>
        <div class='menu_item' id='button_logout'>logout</div>
      </div>
      <div class='fab' id='button_manualrun'>&gt;_</div>
      <div class='hamburger' id="menu_hamburger">
        <div></div>
        <div></div>
        <div></div>
      </div>
    </header>
```

And added the following css:
```css
.hamburger {
  display: none;
  float: right;
}

.menubar {
  display: inline-block;
}

.hamburger div {
  width: 35px;
  height: 5px;
  background-color: black;
  margin: 6px 0;
}

@media(max-width: 800px) {
  .hamburger {
    display: inline-block;
  }

  .menubar {
    display: none;
  }
}


```
